language: rust
cache: cargo
dist: trusty
sudo: false
os:
  - linux

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

rust:
  - nightly
  - beta
  - stable
  - 1.15.1

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
    travis-cargo test

after_success:
  - travis-cargo coveralls --no-sudo --verify

notifications:
  email:
    recipients:
      - gnieto.talo@gmail.com
    on_success: change
    on_failure: always