language: rust
cache: cargo
dist: trusty
sudo: false
os:
  - linux

rust:
  - nightly
  - beta
  - stable
  - 1.15.1

script:
  - cargo test

notifications:
  email:
    recipients:
      - gnieto.talo@gmail.com
    on_success: change
    on_failure: always