language: rust
# cache: cargo
dist: trusty
sudo: true
os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - zlib1g-dev

rust:
  - nightly
  - beta
  - stable
  - 1.26.0

before_script:
  - export PATH=$PATH:~/.cargo/bin
  - ./travis-helper.sh install_deps

script:
  - cargo build
  - cargo build --example converter
  - cargo build --example exporter
  - cargo test
  - cargo package
  - ./travis-helper.sh clippy_run
  - ./travis-helper.sh fmt_run

after_success:
  - ./travis-helper.sh upload_code_coverage
  - ./travis-helper.sh upload_documentation

notifications:
  email:
    recipients:
      - razican@protonmail.ch
      - brunoop@protonmail.ch
      - sergiodlo@protonmail.com
      - jaimesr@protonmail.ch
    on_success: change
    on_failure: always
