language: rust
cache: cargo
dist: trusty
sudo: false
os:
  - linux

env:
  global:
    -cache: cargo

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

rust:
  - nightly
  - beta
  - stable
  - 1.15.1

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - |
      cargo install cargo-travis || true  &&
      export PATH=$HOME/.cargo/bin:$PATH
  - (test $TRAVIS_RUST_VERSION != "stable" || cargo install rustfmt --force)

script:
  - |
    cargo build &&
    cargo build --example converter &&
    cargo build --example exporter &&
    cargo test
  - (test $TRAVIS_RUST_VERSION != "stable" || cargo fmt -- --write-mode=diff)

after_success:
  - cargo coveralls

notifications:
  email:
    recipients:
      - gnieto.talo@gmail.com
    on_success: change
    on_failure: always