language: rust
cache: cargo
dist: trusty
sudo: false
os:
  - linux
  - osx

env:
  global:
    -cache: cargo

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

rust:
  - nightly
  - beta
  - stable
  - 1.20.0

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - |
      cargo install cargo-travis || true  &&
      export PATH=$HOME/.cargo/bin:$PATH
  - (test $TRAVIS_RUST_VERSION != "nightly" || rustup component add rustfmt-preview)

script:
  - |
    cargo build &&
    cargo build --example converter &&
    cargo build --example exporter &&
    cargo test
  - (test $TRAVIS_RUST_VERSION != "nightly" || cargo fmt -- --write-mode=diff)

after_success:
  - cargo coveralls

notifications:
  email:
    recipients:
      - gnieto.talo@gmail.com
    on_success: change
    on_failure: always
