language: rust
dist: trusty
sudo: false
os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

rust:
  - nightly
  - beta
  - stable
  - 1.20.0

before_script:
  - |
      cargo install cargo-travis || true  &&
      export PATH=$HOME/.cargo/bin:$PATH
  - (test $TRAVIS_RUST_VERSION != "stable" || rustup component add rustfmt-preview)

script:
  - |
    cargo build &&
    cargo build --example converter &&
    cargo build --example exporter &&
    cargo test
  - (test $TRAVIS_RUST_VERSION != "stable" || cargo fmt -- --write-mode=diff)

after_success:
  - cargo coveralls

notifications:
  email:
    recipients:
      - razican@protonmail.ch
      - brunoop@protonmail.ch
      - sergiodlo@protonmail.com
      - jaimesr@protonmail.ch
    on_success: change
    on_failure: always
