[package]
name = "abxml"
version = "0.3.0"
license = "MIT/Apache-2.0"
authors = [
    "Guillem Nieto <gnieto.talo@gmail.com>",
    "Iban Eguia <razican@protonmail.ch>"
]
repository = "https://github.com/gnieto/abxml-rs"
description = """
Parser for resources.arsc contained on APKs and binary XML decompresser
"""
keywords = ["android", "arsc", "apk", "parser"]

[dependencies]
byteorder = "1.2.1"
error-chain = "0.11.0"
ansi_term = "0.10.2"
log = "0.4.1"
env_logger = "0.5.0"
zip = { version = "0.3.0", optional = true}
encoding = "0.2.33"
xml-rs = "0.7.0"

[features]
default = ["zip_decode"]
zip_decode = ["zip"]

[[example]]
name = "exporter"
required-features = ["zip_decode"]

[[example]]
name = "converter"
required-features = ["zip_decode"]
