[package]
name = "abxml"
version = "0.1.0"
authors = ["Guillem Nieto <gnieto.talo@gmail.com>"]

[dependencies]
byteorder = "0.5"
quick-xml = "0.4.1"
error-chain = "0.7.1"
ansi_term = "0.9"
log = "0.3.6"
env_logger = "0.3.5"
zip = "0.2"
encode_unicode = "0.2.0"