[package]
name = "abxml"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = ["Guillem Nieto <gnieto.talo@gmail.com>"]
repository = "https://github.com/gnieto/abxml-rs"
description = """
Parser for resources.arsc contained on APKs and binary XML decompresser
"""
keywords = ["android", "arsc", "apk", "parser"]

[dependencies]
byteorder = "0.5"
quick-xml = "0.4.1"
error-chain = "0.7.1"
ansi_term = "0.9"
log = "0.3.6"
env_logger = "0.3.5"
zip = { version = "0.2", optional = true}
encoding = "0.2"

[features]
default = ["zip_decode"]
zip_decode = ["zip"]

[[example]]
name = "exporter"
required-features = ["zip_decode"]