[package]
name = "abxml"
version = "0.3.0"
license = "MIT/Apache-2.0"
authors = ["Guillem Nieto <gnieto.talo@gmail.com>"]
repository = "https://github.com/gnieto/abxml-rs"
description = """
Parser for resources.arsc contained on APKs and binary XML decompresser
"""
keywords = ["android", "arsc", "apk", "parser"]

[dependencies]
byteorder = "^1.0"
error-chain = "^0.10"
ansi_term = "^0.9"
log = "^0.3"
env_logger = "^0.4"
zip = { version = "^0.2", optional = true}
encoding = "^0.2"
xml-rs = "^0.4"

[features]
default = ["zip_decode"]
zip_decode = ["zip"]

[[example]]
name = "exporter"
required-features = ["zip_decode"]

[[example]]
name = "converter"
required-features = ["zip_decode"]
